name: Deploy Site
permissions:
    id-token: write
    pages: write
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bun
      - run: bun install
      - run: bun run build
      - uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: dist
      - uses: actions/deploy-pages@v1.2.9
        with:
          token: ${{ github.token }}
